In [1]:
import gym

env = gym.make('CartPole-v1')
print(env.observation_space)
print(env.action_space)

Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)
Discrete(2)


In [2]:
env.reset()

(array([-0.00686608, -0.00842819,  0.01445066,  0.02200087], dtype=float32),
 {})

In [3]:
print(env.step(action=0))
print(env.step(action=1))

(array([-0.00703465, -0.20375437,  0.01489067,  0.31920788], dtype=float32), 1.0, False, False, {})
(array([-0.01110973, -0.00884762,  0.02127483,  0.03125788], dtype=float32), 1.0, False, False, {})


/home/mys1erious/UserFolder/venvs/ml-raschka-venv/lib/python3.11/site-packages/gym/utils/passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):
